language: bash

stages:
  - build
  - name: publish
#    if: branch = master

services:
  - docker

jobs:
  include: 
    - stage: build
      script: docker build -t ${DOCKERHUB_USER}/wahlzeit .
    - stage: publish
      script: docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PW}
      script: docker push ${DOCKERHUB_USER}/wahlzeit